[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PRODUCTION = "false"

# Ensure API routes are handled as serverless functions
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect API routes to prevent pre-rendering attempts
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true
