[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PRODUCTION = "false"

# Let the Next.js plugin handle all routing automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"
